apiVersion: v1
kind: Pod
metadata:
  name: sws-liveness
spec:
  containers:
    - image: amorokin/sws:1.4
      name: sws
      ports:
      - containerPort: 8080
        protocol: TCP
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 15