apiVersion: v1
kind: ReplicationController
metadata:
  name: sws-rc
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: sws
    spec:
      containers:
        - name: sws
          image: amorokin/sws:v1.3.0
          ports:
            - containerPort: 8080