apiVersion: v1
kind: Pod
metadata:
  name: sws-manual-v2
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
    - image: amorokin/sws:1.4
      name: sws
      ports:
      - containerPort: 8080
        protocol: TCP