apiVersion: v1
kind: PersistentVolume
metadata:
  name: mdb-pv
spec:
  capacity: 
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/mongodb