apiVersion: v1
kind: Pod
metadata:
  name: mdb
spec:
  containers:
  - image: mongo
    name: mongodb
    ports:
    - containerPort: 27017
      protocol: TCP
    volumeMounts:
    - name: mdb-data
      mountPath: /data/db
  volumes:
  - name: mdb-data
    persistentVolumeClaim:
      claimName: mdb-pvc