apiVersion: v1
kind: Pod
metadata:
  name: frt-cm-vol
spec:
  containers:
    - image: luksa/fortune:env
      env:
        - name: INTERVAL
          valueFrom:
            configMapKeyRef:
              name: fortune-config
              key: sleep-interval
      name: html-generator
      volumeMounts:
        - name: html
          mountPath: /var/htdocs
    - image: nginx:alpine
      name: web-server
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
        - name: config
          mountPath: /etc/nginx/conf.d/gzip.conf
          subPath: gzip.conf
          readOnly: true
  volumes:
    - name: html
      emptyDir:
        medium: Memory
    - name: config
      configMap:
        name: fortune-config
        items:
          - key: gzip.conf
            path: gzip.conf
